### ISSUE TITLE
Crash when using --db-only flag

### ISSUE THREAD

**Issue by zxjon22** [zxjon22/trac2gitea#13]
```
issue 379 already exists - ignored
issue 380 already exists - ignored
committing transaction
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x1004930a4]

goroutine 1 [running]:
gopkg.in/src-d/go-git%2ev4.(*Repository).Remote(0x0, {0x1005cfac1, 0x6})
	/Users/xxx/go/pkg/mod/gopkg.in/src-d/go-git.v4@v4.13.1/repository.go:444 +0x24
gopkg.in/src-d/go-git%2ev4.(*Repository).PushContext(0x0?, {0x10079e978, 0x140001a4028}, 0x14000291d48)
	/Users/xxx/go/pkg/mod/gopkg.in/src-d/go-git.v4@v4.13.1/repository.go:1037 +0x48
gopkg.in/src-d/go-git%2ev4.(*Repository).Push(...)
	/Users/xxx/go/pkg/mod/gopkg.in/src-d/go-git.v4@v4.13.1/repository.go:1022
github.com/stevejefferson/trac2gitea/accessor/gitea.(*DefaultAccessor).commitWikiRepo(0x140001fe1b0)
	/Users/xxx/Source/trac2gitea/accessor/gitea/wiki.go:234 +0x118
github.com/stevejefferson/trac2gitea/accessor/gitea.(*DefaultAccessor).CommitTransaction(0x140001fe1b0)
	/Users/xxx/Source/trac2gitea/accessor/gitea/transaction.go:14 +0x40
github.com/stevejefferson/trac2gitea/importer.(*Importer).CommitImport(0x14000236740)
	/Users/xxx/Source/trac2gitea/importer/transaction.go:14 +0x58
main.performImport(0x16fd537fd?, 0x1e?, 0x140000546c8?, 0x140000021a0?, 0x14000054708?, 0x10010f568?, 0x140000021a0?, 0x300000002?, 0x140001e7f28?)
	/Users/xxx/Source/trac2gitea/main.go:175 +0x5c
main.main()
	/Users/xxx/Source/trac2gitea/main.go:252 +0x37c
```

NOTE: The DB changes are actually committed.

**Comment by zxjon22** [comment]
Interestingly, the crash doesn't happen if you also pass `--no-wiki-push`
